from setuptools import setup

setup(
  name='luscious-downloader',
  version='1',
  packages=['venv.Lib.site-packages.pp', 'venv.Lib.site-packages.pox', 'venv.Lib.site-packages.pox.tests',
            'venv.Lib.site-packages.dill', 'venv.Lib.site-packages.dill.tests', 'venv.Lib.site-packages.idna',
            'venv.Lib.site-packages.lxml', 'venv.Lib.site-packages.lxml.html', 'venv.Lib.site-packages.lxml.includes',
            'venv.Lib.site-packages.lxml.isoschematron', 'venv.Lib.site-packages.ppft',
            'venv.Lib.site-packages.ppft.tests', 'venv.Lib.site-packages.ppft.server', 'venv.Lib.site-packages.tqdm',
            'venv.Lib.site-packages.tqdm.auto', 'venv.Lib.site-packages.tqdm.autonotebook',
            'venv.Lib.site-packages.p_tqdm', 'venv.Lib.site-packages.pathos', 'venv.Lib.site-packages.pathos.tests',
            'venv.Lib.site-packages.pathos.secure', 'venv.Lib.site-packages.pathos.xmlrpc',
            'venv.Lib.site-packages.pathos.helpers', 'venv.Lib.site-packages.certifi', 'venv.Lib.site-packages.chardet',
            'venv.Lib.site-packages.chardet.cli', 'venv.Lib.site-packages.urllib3',
            'venv.Lib.site-packages.urllib3.util', 'venv.Lib.site-packages.urllib3.contrib',
            'venv.Lib.site-packages.urllib3.contrib._securetransport', 'venv.Lib.site-packages.urllib3.packages',
            'venv.Lib.site-packages.urllib3.packages.backports',
            'venv.Lib.site-packages.urllib3.packages.ssl_match_hostname', 'venv.Lib.site-packages.requests',
            'venv.Lib.site-packages.selenium', 'venv.Lib.site-packages.selenium.common',
            'venv.Lib.site-packages.selenium.webdriver', 'venv.Lib.site-packages.selenium.webdriver.ie',
            'venv.Lib.site-packages.selenium.webdriver.edge', 'venv.Lib.site-packages.selenium.webdriver.opera',
            'venv.Lib.site-packages.selenium.webdriver.chrome', 'venv.Lib.site-packages.selenium.webdriver.common',
            'venv.Lib.site-packages.selenium.webdriver.common.html5',
            'venv.Lib.site-packages.selenium.webdriver.common.actions',
            'venv.Lib.site-packages.selenium.webdriver.remote', 'venv.Lib.site-packages.selenium.webdriver.safari',
            'venv.Lib.site-packages.selenium.webdriver.android', 'venv.Lib.site-packages.selenium.webdriver.firefox',
            'venv.Lib.site-packages.selenium.webdriver.support', 'venv.Lib.site-packages.selenium.webdriver.phantomjs',
            'venv.Lib.site-packages.selenium.webdriver.webkitgtk',
            'venv.Lib.site-packages.selenium.webdriver.blackberry', 'venv.Lib.site-packages.pyreadline',
            'venv.Lib.site-packages.pyreadline.test', 'venv.Lib.site-packages.pyreadline.modes',
            'venv.Lib.site-packages.pyreadline.console', 'venv.Lib.site-packages.pyreadline.keysyms',
            'venv.Lib.site-packages.pyreadline.clipboard', 'venv.Lib.site-packages.pyreadline.lineeditor',
            'venv.Lib.site-packages.multiprocess', 'venv.Lib.site-packages.multiprocess.dummy',
            'venv.Lib.site-packages.multiprocess.tests', 'python.Lib.site-packages.pp', 'python.Lib.site-packages.pip',
            'python.Lib.site-packages.pip._vendor', 'python.Lib.site-packages.pip._vendor.idna',
            'python.Lib.site-packages.pip._vendor.pep517', 'python.Lib.site-packages.pip._vendor.pytoml',
            'python.Lib.site-packages.pip._vendor.certifi', 'python.Lib.site-packages.pip._vendor.chardet',
            'python.Lib.site-packages.pip._vendor.chardet.cli', 'python.Lib.site-packages.pip._vendor.distlib',
            'python.Lib.site-packages.pip._vendor.distlib._backport', 'python.Lib.site-packages.pip._vendor.msgpack',
            'python.Lib.site-packages.pip._vendor.urllib3', 'python.Lib.site-packages.pip._vendor.urllib3.util',
            'python.Lib.site-packages.pip._vendor.urllib3.contrib',
            'python.Lib.site-packages.pip._vendor.urllib3.contrib._securetransport',
            'python.Lib.site-packages.pip._vendor.urllib3.packages',
            'python.Lib.site-packages.pip._vendor.urllib3.packages.backports',
            'python.Lib.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
            'python.Lib.site-packages.pip._vendor.colorama', 'python.Lib.site-packages.pip._vendor.html5lib',
            'python.Lib.site-packages.pip._vendor.html5lib._trie',
            'python.Lib.site-packages.pip._vendor.html5lib.filters',
            'python.Lib.site-packages.pip._vendor.html5lib.treewalkers',
            'python.Lib.site-packages.pip._vendor.html5lib.treeadapters',
            'python.Lib.site-packages.pip._vendor.html5lib.treebuilders',
            'python.Lib.site-packages.pip._vendor.lockfile', 'python.Lib.site-packages.pip._vendor.progress',
            'python.Lib.site-packages.pip._vendor.requests', 'python.Lib.site-packages.pip._vendor.packaging',
            'python.Lib.site-packages.pip._vendor.cachecontrol',
            'python.Lib.site-packages.pip._vendor.cachecontrol.caches',
            'python.Lib.site-packages.pip._vendor.webencodings', 'python.Lib.site-packages.pip._vendor.pkg_resources',
            'python.Lib.site-packages.pip._internal', 'python.Lib.site-packages.pip._internal.cli',
            'python.Lib.site-packages.pip._internal.req', 'python.Lib.site-packages.pip._internal.vcs',
            'python.Lib.site-packages.pip._internal.utils', 'python.Lib.site-packages.pip._internal.models',
            'python.Lib.site-packages.pip._internal.commands', 'python.Lib.site-packages.pip._internal.operations',
            'python.Lib.site-packages.pox', 'python.Lib.site-packages.pox.tests', 'python.Lib.site-packages.dill',
            'python.Lib.site-packages.dill.tests', 'python.Lib.site-packages.idna', 'python.Lib.site-packages.lxml',
            'python.Lib.site-packages.lxml.html', 'python.Lib.site-packages.lxml.includes',
            'python.Lib.site-packages.lxml.isoschematron', 'python.Lib.site-packages.ppft',
            'python.Lib.site-packages.ppft.tests', 'python.Lib.site-packages.ppft.server',
            'python.Lib.site-packages.tqdm', 'python.Lib.site-packages.tqdm.auto',
            'python.Lib.site-packages.tqdm.autonotebook', 'python.Lib.site-packages.wheel',
            'python.Lib.site-packages.wheel.cli', 'python.Lib.site-packages.p_tqdm', 'python.Lib.site-packages.pathos',
            'python.Lib.site-packages.pathos.tests', 'python.Lib.site-packages.pathos.secure',
            'python.Lib.site-packages.pathos.xmlrpc', 'python.Lib.site-packages.pathos.helpers',
            'python.Lib.site-packages.certifi', 'python.Lib.site-packages.chardet',
            'python.Lib.site-packages.chardet.cli', 'python.Lib.site-packages.urllib3',
            'python.Lib.site-packages.urllib3.util', 'python.Lib.site-packages.urllib3.contrib',
            'python.Lib.site-packages.urllib3.contrib._securetransport', 'python.Lib.site-packages.urllib3.packages',
            'python.Lib.site-packages.urllib3.packages.backports',
            'python.Lib.site-packages.urllib3.packages.ssl_match_hostname', 'python.Lib.site-packages.requests',
            'python.Lib.site-packages.selenium', 'python.Lib.site-packages.selenium.common',
            'python.Lib.site-packages.selenium.webdriver', 'python.Lib.site-packages.selenium.webdriver.ie',
            'python.Lib.site-packages.selenium.webdriver.edge', 'python.Lib.site-packages.selenium.webdriver.opera',
            'python.Lib.site-packages.selenium.webdriver.chrome', 'python.Lib.site-packages.selenium.webdriver.common',
            'python.Lib.site-packages.selenium.webdriver.common.html5',
            'python.Lib.site-packages.selenium.webdriver.common.actions',
            'python.Lib.site-packages.selenium.webdriver.remote', 'python.Lib.site-packages.selenium.webdriver.safari',
            'python.Lib.site-packages.selenium.webdriver.android',
            'python.Lib.site-packages.selenium.webdriver.firefox',
            'python.Lib.site-packages.selenium.webdriver.support',
            'python.Lib.site-packages.selenium.webdriver.phantomjs',
            'python.Lib.site-packages.selenium.webdriver.webkitgtk',
            'python.Lib.site-packages.selenium.webdriver.blackberry', 'python.Lib.site-packages.pyreadline',
            'python.Lib.site-packages.pyreadline.test', 'python.Lib.site-packages.pyreadline.modes',
            'python.Lib.site-packages.pyreadline.console', 'python.Lib.site-packages.pyreadline.keysyms',
            'python.Lib.site-packages.pyreadline.clipboard', 'python.Lib.site-packages.pyreadline.lineeditor',
            'python.Lib.site-packages.setuptools', 'python.Lib.site-packages.setuptools.extern',
            'python.Lib.site-packages.setuptools._vendor', 'python.Lib.site-packages.setuptools._vendor.packaging',
            'python.Lib.site-packages.setuptools.command', 'python.Lib.site-packages.multiprocess',
            'python.Lib.site-packages.multiprocess.dummy', 'python.Lib.site-packages.multiprocess.tests',
            'python.Lib.site-packages.pkg_resources', 'python.Lib.site-packages.pkg_resources.extern',
            'python.Lib.site-packages.pkg_resources._vendor',
            'python.Lib.site-packages.pkg_resources._vendor.packaging'],
  url='https://github.com/Lucas8x/luscious-downloader',
  license='GPL',
  author='Lucas8x',
  author_email='',
  description='Auto Download Luscious Pictures'
)
