from setuptools import setup

setup(
    name='luscious-downloader',
    version='1.0',
    packages=['venv.Lib.site-packages.pp', 'venv.Lib.site-packages.pip', 'venv.Lib.site-packages.pip._vendor',
              'venv.Lib.site-packages.pip._vendor.idna', 'venv.Lib.site-packages.pip._vendor.pep517',
              'venv.Lib.site-packages.pip._vendor.pytoml', 'venv.Lib.site-packages.pip._vendor.certifi',
              'venv.Lib.site-packages.pip._vendor.chardet', 'venv.Lib.site-packages.pip._vendor.chardet.cli',
              'venv.Lib.site-packages.pip._vendor.distlib', 'venv.Lib.site-packages.pip._vendor.distlib._backport',
              'venv.Lib.site-packages.pip._vendor.msgpack', 'venv.Lib.site-packages.pip._vendor.urllib3',
              'venv.Lib.site-packages.pip._vendor.urllib3.util', 'venv.Lib.site-packages.pip._vendor.urllib3.contrib',
              'venv.Lib.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.Lib.site-packages.pip._vendor.urllib3.packages',
              'venv.Lib.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.Lib.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.Lib.site-packages.pip._vendor.colorama', 'venv.Lib.site-packages.pip._vendor.html5lib',
              'venv.Lib.site-packages.pip._vendor.html5lib._trie',
              'venv.Lib.site-packages.pip._vendor.html5lib.filters',
              'venv.Lib.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.Lib.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.Lib.site-packages.pip._vendor.html5lib.treebuilders', 'venv.Lib.site-packages.pip._vendor.lockfile',
              'venv.Lib.site-packages.pip._vendor.progress', 'venv.Lib.site-packages.pip._vendor.requests',
              'venv.Lib.site-packages.pip._vendor.packaging', 'venv.Lib.site-packages.pip._vendor.cachecontrol',
              'venv.Lib.site-packages.pip._vendor.cachecontrol.caches',
              'venv.Lib.site-packages.pip._vendor.webencodings', 'venv.Lib.site-packages.pip._vendor.pkg_resources',
              'venv.Lib.site-packages.pip._internal', 'venv.Lib.site-packages.pip._internal.cli',
              'venv.Lib.site-packages.pip._internal.req', 'venv.Lib.site-packages.pip._internal.vcs',
              'venv.Lib.site-packages.pip._internal.utils', 'venv.Lib.site-packages.pip._internal.models',
              'venv.Lib.site-packages.pip._internal.commands', 'venv.Lib.site-packages.pip._internal.operations',
              'venv.Lib.site-packages.pox', 'venv.Lib.site-packages.pox.tests', 'venv.Lib.site-packages.dill',
              'venv.Lib.site-packages.dill.tests', 'venv.Lib.site-packages.idna', 'venv.Lib.site-packages.lxml',
              'venv.Lib.site-packages.lxml.html', 'venv.Lib.site-packages.lxml.includes',
              'venv.Lib.site-packages.lxml.isoschematron', 'venv.Lib.site-packages.ppft',
              'venv.Lib.site-packages.ppft.tests', 'venv.Lib.site-packages.ppft.server', 'venv.Lib.site-packages.tqdm',
              'venv.Lib.site-packages.tqdm.auto', 'venv.Lib.site-packages.tqdm.autonotebook',
              'venv.Lib.site-packages.venv.Lib.site-packages.lxml',
              'venv.Lib.site-packages.venv.Lib.site-packages.lxml.html',
              'venv.Lib.site-packages.venv.Lib.site-packages.lxml.includes',
              'venv.Lib.site-packages.venv.Lib.site-packages.lxml.isoschematron',
              'venv.Lib.site-packages.venv.Lib.site-packages.tqdm',
              'venv.Lib.site-packages.venv.Lib.site-packages.tqdm.auto',
              'venv.Lib.site-packages.venv.Lib.site-packages.tqdm.autonotebook',
              'venv.Lib.site-packages.venv.Lib.site-packages.urllib3',
              'venv.Lib.site-packages.venv.Lib.site-packages.urllib3.util',
              'venv.Lib.site-packages.venv.Lib.site-packages.urllib3.contrib',
              'venv.Lib.site-packages.venv.Lib.site-packages.urllib3.contrib._securetransport',
              'venv.Lib.site-packages.venv.Lib.site-packages.urllib3.packages',
              'venv.Lib.site-packages.venv.Lib.site-packages.urllib3.packages.backports',
              'venv.Lib.site-packages.venv.Lib.site-packages.urllib3.packages.ssl_match_hostname',
              'venv.Lib.site-packages.venv.Lib.site-packages.selenium',
              'venv.Lib.site-packages.venv.Lib.site-packages.selenium.common',
              'venv.Lib.site-packages.venv.Lib.site-packages.selenium.webdriver',
              'venv.Lib.site-packages.venv.Lib.site-packages.selenium.webdriver.ie',
              'venv.Lib.site-packages.venv.Lib.site-packages.selenium.webdriver.edge',
              'venv.Lib.site-packages.venv.Lib.site-packages.selenium.webdriver.opera',
              'venv.Lib.site-packages.venv.Lib.site-packages.selenium.webdriver.chrome',
              'venv.Lib.site-packages.venv.Lib.site-packages.selenium.webdriver.common',
              'venv.Lib.site-packages.venv.Lib.site-packages.selenium.webdriver.common.html5',
              'venv.Lib.site-packages.venv.Lib.site-packages.selenium.webdriver.common.actions',
              'venv.Lib.site-packages.venv.Lib.site-packages.selenium.webdriver.remote',
              'venv.Lib.site-packages.venv.Lib.site-packages.selenium.webdriver.safari',
              'venv.Lib.site-packages.venv.Lib.site-packages.selenium.webdriver.android',
              'venv.Lib.site-packages.venv.Lib.site-packages.selenium.webdriver.firefox',
              'venv.Lib.site-packages.venv.Lib.site-packages.selenium.webdriver.support',
              'venv.Lib.site-packages.venv.Lib.site-packages.selenium.webdriver.phantomjs',
              'venv.Lib.site-packages.venv.Lib.site-packages.selenium.webdriver.webkitgtk',
              'venv.Lib.site-packages.venv.Lib.site-packages.selenium.webdriver.blackberry',
              'venv.Lib.site-packages.p_tqdm', 'venv.Lib.site-packages.pathos', 'venv.Lib.site-packages.pathos.tests',
              'venv.Lib.site-packages.pathos.secure', 'venv.Lib.site-packages.pathos.xmlrpc',
              'venv.Lib.site-packages.pathos.helpers', 'venv.Lib.site-packages.certifi',
              'venv.Lib.site-packages.chardet', 'venv.Lib.site-packages.chardet.cli', 'venv.Lib.site-packages.urllib3',
              'venv.Lib.site-packages.urllib3.util', 'venv.Lib.site-packages.urllib3.contrib',
              'venv.Lib.site-packages.urllib3.contrib._securetransport', 'venv.Lib.site-packages.urllib3.packages',
              'venv.Lib.site-packages.urllib3.packages.backports',
              'venv.Lib.site-packages.urllib3.packages.ssl_match_hostname', 'venv.Lib.site-packages.colorama',
              'venv.Lib.site-packages.requests', 'venv.Lib.site-packages.selenium',
              'venv.Lib.site-packages.selenium.common', 'venv.Lib.site-packages.selenium.webdriver',
              'venv.Lib.site-packages.selenium.webdriver.ie', 'venv.Lib.site-packages.selenium.webdriver.edge',
              'venv.Lib.site-packages.selenium.webdriver.opera', 'venv.Lib.site-packages.selenium.webdriver.chrome',
              'venv.Lib.site-packages.selenium.webdriver.common',
              'venv.Lib.site-packages.selenium.webdriver.common.html5',
              'venv.Lib.site-packages.selenium.webdriver.common.actions',
              'venv.Lib.site-packages.selenium.webdriver.remote', 'venv.Lib.site-packages.selenium.webdriver.safari',
              'venv.Lib.site-packages.selenium.webdriver.android', 'venv.Lib.site-packages.selenium.webdriver.firefox',
              'venv.Lib.site-packages.selenium.webdriver.support',
              'venv.Lib.site-packages.selenium.webdriver.phantomjs',
              'venv.Lib.site-packages.selenium.webdriver.webkitgtk',
              'venv.Lib.site-packages.selenium.webdriver.blackberry', 'venv.Lib.site-packages.pyreadline',
              'venv.Lib.site-packages.pyreadline.test', 'venv.Lib.site-packages.pyreadline.modes',
              'venv.Lib.site-packages.pyreadline.console', 'venv.Lib.site-packages.pyreadline.keysyms',
              'venv.Lib.site-packages.pyreadline.clipboard', 'venv.Lib.site-packages.pyreadline.lineeditor',
              'venv.Lib.site-packages.setuptools', 'venv.Lib.site-packages.setuptools.extern',
              'venv.Lib.site-packages.setuptools._vendor', 'venv.Lib.site-packages.setuptools._vendor.packaging',
              'venv.Lib.site-packages.setuptools.command', 'venv.Lib.site-packages.multiprocess',
              'venv.Lib.site-packages.multiprocess.dummy', 'venv.Lib.site-packages.multiprocess.tests',
              'venv.Lib.site-packages.pkg_resources', 'venv.Lib.site-packages.pkg_resources.extern',
              'venv.Lib.site-packages.pkg_resources._vendor', 'venv.Lib.site-packages.pkg_resources._vendor.packaging'],
    url='',
    license='',
    author='Lucas8x',
    author_email='',
    description='Auto Download Luscious Albums'
)
